neoforge_version=21.11.45
packs=options-list,screen-field,world-gamerules,input-event,text-components,server-119,use-stack,pixels-argb,quads-vec,state-list,tints-array,resolver-owner,cmds-equipment
label=1.21.11
mc_range=[1.21.11]
neoforge_range=[21.11,)
java=21
