neoforge_version=21.9.16-beta
packs=options-list-legacy,screen-field,world-flags,input-event,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-owner,cmds-equipment
label=1.21.9-1.21.10
mc_range=[1.21.9,1.21.11)
neoforge_range=[21.9,21.11)
java=21
