neoforge_version=21.5.98
packs=options-list-legacy,screen-field,world-flags,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-living,cmds-equipment
label=1.21.5
mc_range=[1.21.5]
neoforge_range=[21.5,21.6)
java=21
