neoforge_version=21.4.157
packs=options-list-legacy,world-flags,screen-field,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-class,model-proxy,state-model,tints-array,cmds-components
label=1.21.4
mc_range=[1.21.4]
neoforge_range=[21.4,21.5)
java=21
