neoforge_version=21.6.20-beta
packs=options-list-legacy,screen-field,world-flags,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-living,cmds-equipment
label=1.21.6-1.21.8
mc_range=[1.21.6,1.21.9)
neoforge_range=[21.6,21.9)
java=21
