neoforge_version=21.2.1-beta
packs=options-list-legacy,world-flags,screen-field,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-class,model-proxy,render-model,cmds-components
label=1.21.2-1.21.3
mc_range=[1.21.2,1.21.4)
neoforge_range=[21.2,21.4)
java=21
