neoforge_version=21.10.64
packs=options-list-legacy,screen-field,world-flags,input-event,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-owner,cmds-equipment
label=1.21.10
mc_range=[1.21.10]
neoforge_range=[21.10,21.11)
java=21
