neoforge_version=21.1.251
packs=options-list-legacy,world-rules,screen-field,input-legacy,text-components,server-119,use-food,pixels-abgr,quads-class-legacy,model-proxy,render-model,cmds-components
label=1.21.1
mc_range=[1.21.1]
neoforge_range=[21.1,21.2)
java=21
food_mods=maven.modrinth:farmers-delight:1.21.1-1.3.4
