neoforge_version=21.3.97
packs=options-list-legacy,world-flags,screen-field,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-class,model-proxy,render-model,cmds-components
label=1.21.3
mc_range=[1.21.3]
neoforge_range=[21.3,21.4)
java=21
