neoforge_version=26.1.0.19-beta
packs=options-list,screen-field,world-difficulty,input-event,text-components,server-119,use-template,pixels-argb,quads-material,state-list,tints-intlist,resolver-owner,cmds-equipment
label=26.1-26.1.2
mc_range=[26.1,26.2)
neoforge_range=[26.1,26.2)
java=25
