modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/comedy01/Munch/issues"

[[mods]]
modId="munch"
version="${version}"
displayName="Munch"
displayURL="https://github.com/comedy01/Munch"
iconFile="assets/munch/icon128.png"
authors="comedy01"
description='''Eating and drinking animations. Food gets bitten down with every chew, and drinks drain as you sip, for every food and drink, modded ones included. Client-side only.'''

[[mixins]]
config="munch.mixins.json"

[[dependencies.munch]]
modId="neoforge"
type="required"
versionRange="${neoforge_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.munch]]
modId="minecraft"
type="required"
versionRange="${mc_range}"
ordering="NONE"
side="CLIENT"
