fabric_api_version=0.91.6+1.20.2
modmenu_version=8.0.1
packs=options-grid,world-legacy,screen-field,input-legacy,text-components,server-119,use-tags,pixels-abgr,quads-class-legacy,model-proxy,render-model,cmds-nbt
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
