fabric_api_version=0.97.3+1.20.4
modmenu_version=9.2.0
packs=options-grid,world-rules,screen-field,input-legacy,text-components,server-119,use-tags,pixels-abgr,quads-class-legacy,model-proxy,render-model,cmds-nbt
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
