fabric_api_version=0.100.8+1.20.6
modmenu_version=10.0.0
packs=options-grid,world-rules,screen-field,input-legacy,text-components,server-119,use-bowl,pixels-abgr,quads-class-legacy,model-proxy,render-model,cmds-components
label=1.20.5-1.20.6
range=>=1.20.5 <1.21
java=21
