fabric_api_version=0.116.17+1.21.1
modmenu_version=11.0.4
packs=options-list-legacy,world-rules,screen-field,input-legacy,text-components,server-119,use-food,pixels-abgr,quads-class-legacy,model-proxy,render-model,cmds-components
label=1.21-1.21.1
range=>=1.21 <1.21.2
java=21
