fabric_api_version=0.106.1+1.21.2
modmenu_version=12.0.1
packs=options-list-legacy,world-flags,screen-field,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-class,model-proxy,render-model,cmds-components
label=1.21.2-1.21.3
range=>=1.21.2 <1.21.4
java=21
