fabric_api_version=0.119.4+1.21.4
modmenu_version=13.0.4
packs=options-list-legacy,world-flags,screen-field,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-class,model-proxy,state-model,tints-array,cmds-components
label=1.21.4
range=1.21.4
java=21
