fabric_api_version=0.134.1+1.21.9
modmenu_version=16.0.1
packs=options-list-legacy,screen-field,world-flags,input-event,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-owner,cmds-equipment
label=1.21.9-1.21.10
range=>=1.21.9 <1.21.11
java=21
