fabric_api_version=0.128.2+1.21.6
modmenu_version=15.0.2
packs=options-list-legacy,screen-field,world-flags,input-legacy,text-components,server-119,use-stack,pixels-argb,quads-record,state-list,tints-array,resolver-living,cmds-equipment
label=1.21.6-1.21.8
range=>=1.21.6 <1.21.9
java=21
