fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
packs=options-list,screen-field,world-difficulty,input-event,text-components,server-119,use-template,pixels-argb,quads-material,state-list,tints-intlist,resolver-owner,cmds-equipment
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
