fabric_api_version=0.161.0+26.3
modmenu_version=21.0.0
packs=text-components,options-list,screen-gui,world-difficulty,server-119,input-event,use-template,pixels-argb,quads-material,state-itemquads,cmds-equipment
label=26.3
range=>=26.3 <26.4
java=25
food_mods=maven.modrinth:farmers-delight-refabricated:26.3-3.6.27,maven.modrinth:delight-lib:26.09.16-26.3-fabric,maven.modrinth:more-delight:26.09.16-26.3-fabric,maven.modrinth:ubes-delight:26.3-0.4.15
